name: Update MaxMind Database

on:
  schedule:
    - cron: "0 0 */7 * *"
  workflow_dispatch:

jobs:
  update-maxmind:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x action.sh

      - name: Run MaxMind Database Update Script
        env:
          MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}
        run: bash action.sh

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Updated MaxMind databases on $(date "+%Y/%m/%d %H:%M:%S")"
          git push
